// 3DSINFLD — faithful port of COMAN (the shipped MAIN/DATA/3DSINFLD.EXE).
//
// The shipped EXE is COMAN/MAIN.C + ASM.ASM + THELOOP.INC (+ DIS), proven by
// unpacking the double-compressed binary (PKLITE 1.14 outer layer, decoded
// with the stub's own bit trees, then the LINK /E EXEPACK layer, decoded with
// the RB-signature stub's backward RLE) and comparing:
//   - THELOOP.OBJ === image bytes at 0x4890 (0 diffs, 16574 bytes);
//   - ASM.OBJ === image bytes at 0x5A0 (only the 3 link-fixup bytes of
//     `call theloop` differ), so ASM.ASM is authoritative and the IFDEF'd
//     PXLSUX/combguse background blit is NOT in the shipped docopy (no
//     `mov cx,60` anywhere in the binary): the backdrop really is black and
//     COMBG.UH/combguse are dead weight (combguse is filled, never blitted);
//   - W1DTA.BIN/W2DTA.BIN === image bytes at 0x9440/0x19440 === the CALCW12
//     generator in MAIN.C run over WAVE.H with MS C rand() (seed 1,
//     x = x*214013+2531011, return (x>>16)&0x7fff) — all byte-exact;
//   - MAIN.C's doit()/main() match the disassembly instruction for
//     instruction (every constant below is read out of that disassembly).
//
// Timing gates (disassembly at image 0x40..0x88 and 0x94..0xd6):
//   - entry busy-wait `while(!dis_exit() && dis_musplus()<0)`;
//   - main loop cap frame<4444 (`cmp si,0x115c`);
//   - break when musplus is in (-8,0), i.e. -7..-1 (`cmp di,-8 / jle`,
//     `or di,di / jge`);
//   - musplus in (-30,0) drives startrise+=1 while startrise<160 (rise-out);
//   - frame<400 && startrise>0 drives startrise-=1 (descent 160->0); the
//     frame==4 setpalarea re-sends the palette that is already loaded (the
//     port keeps sinfieldPal loaded from reset, as main() does before doit).
//
// Renderer, from THELOOP.INC (generated by a DOLOOP.C variant; the committed
// INC is byte-identical to the shipped THELOOP.OBJ and is what the block
// tables below are validated against by tools/validate_water_grid.mjs):
//   - 128 blocks: j=0..63 single-step, then j=64,66,..,190 double-step
//     (`if(sina==2) j++` in the generator skips odd distances);
//   - per block: si+=xadd (doubled in far blocks), bx = wave1[si] + wave2[di]
//     + zwave[j]-240 with zwave[j]=trunc(16*sin(j*2*pi*3/192)) (16-bit adds);
//   - hit colour = ((bx + 140 - j/8) & 0xff) >> 1  (`lea dx,[bx+140-j/8]` /
//     `shr dl,1` — only the low byte is shifted, so colours are 0..127);
//   - ray height eax and direction ecx are 16.16 fixed point stored
//     word-swapped (integer part in the LOW word) so `cmp ax,bx` compares
//     integer parts directly; fraction carries propagate through
//     `adc ax,0`/`adc cx,0`; per plotted row the ray rises by flip(j*2560)
//     and the direction steepens by flip(2560) per row; eax starts at 0 and
//     ecx at 0xEC00FFFA = flip(-(200-70)*2560) (horizony=70);
//   - vbuf is a 160x200-in-64KiB column buffer (bp wraps at 16 bits exactly
//     like the DOS halloc(16384,4) block), column a occupies byte
//     (a&1)*80+(a>>1) of each row so every ray doubles to 2 screen pixels.
// docopy (ASM.ASM, PXLSUX disabled): unchained VGA with map mask 0x3/0xC —
// vbuf rows 60..199 land on rows startrise+70..startrise+209 of a
// 0x0000/0x8000 page while CRTC 0x0C only ever selects the page top, which is
// how the landscape rides up into view during the descent and back down
// during the rise-out; page rows startrise+52..69 are cleared each frame and
// vbuf rows 68..97 are cleared after the copy.
//
// Palette (main() at image 0x2d3..0x43b): entry (223-a*22/26): green
// (230-a)/4 + sin1024[a*4]/32 clamped 0..63, blue (255-a)/3 clamped,
// red (40-min(|a-220|,40))/3; then bytes 0..719 scaled *9/6 clamped; entries
// 255..232 get a red tail (a-4)/2; entry 0 black.  The final
// `for(x=720;x<768;x++) palette[x]=combg[16+x];` copy is a proven no-op: the
// never-linked 16-byte combg stub sits at image 0x29442 immediately before
// palette[] at 0x29452 in the same far segment, so combg[16+x] IS palette[x].
// Only colours 0..127 are ever drawn, so entries 128..255 are invisible.
//
// sin1024[i] = trunc(sin(i*2*pi/1024)*256) — byte-identical to
// COMAN/SIN1024.INC and to the shipped image at 0x5AE.
//
// Wave tables: assets/coman_w1.bin / coman_w2.bin are byte-exact copies of
// COMAN/W1DTA.BIN / W2DTA.BIN (created by tools/extract_coman_assets.mjs),
// themselves proven identical to the shipped EXE's linked tables.

const VBLANK_HZ = 70;
const WIDTH = 320;
const HEIGHT = 200;

export const sinfieldVram = new Uint8Array(WIDTH * HEIGHT);
export const sinfieldPal = new Uint8Array(768);

const trunc = Math.trunc;

let sin1024 = null;      // Int16Array(1024)
let wave1 = null;        // Int16Array(32768)
let wave2 = null;        // Int16Array(32768)
let basePalette = null;  // Uint8Array(768), fixed for the whole part

// THELOOP.INC per-block constants (128 blocks).
const BLOCKS = 128;
const blockZAdd = new Int32Array(BLOCKS);    // zwave[j] - 240
const blockColour = new Int32Array(BLOCKS);  // 140 - j/8
const blockStep = new Uint32Array(BLOCKS);   // flip(j*2560)
const STEP1 = 0x0a000000 >>> 0;              // flip(2560)
const STEP3 = 0x1e000000 >>> 0;              // flip(3*2560)
const ECX_INIT = 0xec00fffa >>> 0;           // flip(-(200-70)*2560)

// VGA state: 4 planes x 64KiB plane addresses (page A at 0x0000, page B at
// 0x8000), plus the 64KiB vbuf column buffer (16-bit wrap like the original).
const planes = new Uint8Array(4 * 65536);
const vbuf = new Uint8Array(65536);

let startrise = 160;
let rot = 0;
let rot2 = 0;
let xwav = 0;
let ywav = 0;
let flip = 0;
let displayStart = 0; // the mode 13h set leaves the CRTC start at page A
let localFrame = -1;
let drawnFrames = 0;
let done = false;
let doneAtLocal = null;
let musicGateOpen = false;

function wflip(value) {
  // MAIN.C/DOLOOP.C store 16.16 values word-swapped: integer part in the low
  // word, fraction in the high word.
  const v = value >>> 0;
  return (((v & 0xffff) << 16) | (v >>> 16)) >>> 0;
}

function buildTables() {
  sin1024 = new Int16Array(1024);
  for (let i = 0; i < 1024; i++)
    sin1024[i] = trunc(Math.sin(i * Math.PI * 2 / 1024) * 256);
  for (let bi = 0; bi < BLOCKS; bi++) {
    const j = bi < 64 ? bi : 64 + (bi - 64) * 2;
    blockZAdd[bi] = trunc(16 * Math.sin(j * 3.1415926535 * 2 * 3 / 192)) - 240;
    blockColour[bi] = 140 - trunc(j / 8);
    blockStep[bi] = wflip(j * 2560);
  }
}

function buildPalette() {
  const pal = new Uint8Array(768); // char palette[768] is zero-filled BSS
  for (let a = 0; a < 256; a++) {
    const uc = (223 - trunc(a * 22 / 26)) * 3;
    let b = trunc((230 - a) / 4);
    b += trunc(sin1024[(a * 4) & 1023] / 32);
    if (b < 0) b = 0;
    if (b > 63) b = 63;
    pal[uc + 1] = b;
    b = trunc((255 - a) / 3);
    if (b > 63) b = 63;
    pal[uc + 2] = b;
    b = a - 220;
    if (b < 0) b = -b;
    if (b > 40) b = 40;
    b = 40 - b;
    pal[uc + 0] = trunc(b / 3);
  }
  for (let i = 0; i < 768 - 16 * 3; i++) {
    let b = trunc(pal[i] * 9 / 6);
    if (b > 63) b = 63;
    pal[i] = b;
  }
  for (let a = 0; a < 24; a++) {
    const uc = (255 - a) * 3;
    let b = a - 4;
    if (b < 0) b = 0;
    pal[uc + 0] = trunc(b / 2);
    pal[uc + 1] = 0;
    pal[uc + 2] = 0;
  }
  pal[0] = 0;
  pal[1] = 0;
  pal[2] = 0;
  // `for(x=720;x<768;x++) palette[x]=combg[16+x];` — no-op, see header.
  basePalette = pal;
}

async function bytesFrom(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url}: HTTP ${response.status}`);
  return new Uint8Array(await response.arrayBuffer());
}

function wordsOf(bytes) {
  const words = new Int16Array(bytes.length >> 1);
  for (let i = 0; i < words.length; i++)
    words[i] = (bytes[2 * i] | (bytes[2 * i + 1] << 8)) << 16 >> 16;
  return words;
}

export async function loadSinfield() {
  const [w1, w2] = await Promise.all([
    bytesFrom('assets/coman_w1.bin'),
    bytesFrom('assets/coman_w2.bin'),
  ]);
  if (w1.length !== 65536 || w2.length !== 65536)
    throw new Error(`COMAN wave tables: expected 65536+65536 bytes, got ${w1.length}+${w2.length}`);
  wave1 = wordsOf(w1);
  wave2 = wordsOf(w2);
  buildTables();
  buildPalette();
  console.log('[3DSINFLD] COMAN wave tables, sin1024 and palette ready');
}

function musicPosition(sample) {
  if (sample && typeof sample === 'object') {
    return {
      musplus: Number(sample.musplus ?? sample.plus ?? -32),
      exit: sample.exit === true,
    };
  }
  return { musplus: Number(sample ?? -32), exit: false };
}

export function sinfieldReset() {
  planes.fill(0);   // inittwk + memset(vram,0,64000) clear both pages
  vbuf.fill(0);     // halloc zero-fills the column buffer
  sinfieldVram.fill(0);
  if (basePalette) sinfieldPal.set(basePalette); // set before doit() runs
  else sinfieldPal.fill(0);
  startrise = 160;
  rot = 0;
  rot2 = 0;
  xwav = 0;
  ywav = 0;
  flip = 0;          // static int flip: first frame draws page B, shows A
  displayStart = 0;
  localFrame = -1;
  drawnFrames = 0;
  done = false;
  doneAtLocal = null;
  musicGateOpen = false;
}

// THELOOP.INC exact register simulation for one 160-ray column.
function theloop(xw, yw, xadd, yadd, bpStart) {
  let si = (xw & ~1) & 0xffff;
  let di = (yw & ~1) & 0xffff;
  const xs1 = (xadd & ~1) & 0xffff;
  const ys1 = (yadd & ~1) & 0xffff;
  const xs2 = (xs1 + xs1) & 0xffff; // `add cx,cx` wraps at 16 bits
  const ys2 = (ys1 + ys1) & 0xffff;
  let bp = bpStart & 0xffff;
  let eax = 0;
  let ecx = ECX_INIT;
  let cf = 0;

  for (let bi = 0; bi < BLOCKS; bi++) {
    const far = bi >= 64;
    si = (si + (far ? xs2 : xs1)) & 0xffff;
    di = (di + (far ? ys2 : ys1)) & 0xffff;
    const bx = (wave1[si >>> 1] + wave2[di >>> 1] + blockZAdd[bi]) & 0xffff;
    const bxs = bx << 16 >> 16;
    const step = blockStep[bi];

    if ((eax << 16 >> 16) < bxs) {
      const colour = ((bx + blockColour[bi]) & 0xff) >> 1;
      hit: for (;;) {
        // add eax,step ; adc ax,0 ; mov es:[bp],dl
        let sum = eax + step;
        cf = sum > 0xffffffff ? 1 : 0;
        eax = sum >>> 0;
        if (cf) eax = ((eax & 0xffff0000) | (((eax & 0xffff) + 1) & 0xffff)) >>> 0;
        vbuf[bp] = colour;
        if ((eax << 16 >> 16) >= bxs) {
          // jge _@seek1a — the pending carry is the CF of `cmp ax,bx`
          cf = (eax & 0xffff) < bx ? 1 : 0;
          sum = ecx + STEP1 + cf;                       // adc ecx,flip(2560)
          cf = sum > 0xffffffff ? 1 : 0;
          ecx = sum >>> 0;
          if (cf) ecx = ((ecx & 0xffff0000) | (((ecx & 0xffff) + 1) & 0xffff)) >>> 0;
          bp = (bp - 160) & 0xffff;
          break hit;
        }
        sum = eax + step;
        cf = sum > 0xffffffff ? 1 : 0;
        eax = sum >>> 0;
        if (cf) eax = ((eax & 0xffff0000) | (((eax & 0xffff) + 1) & 0xffff)) >>> 0;
        vbuf[(bp - 160) & 0xffff] = colour;
        if ((eax << 16 >> 16) >= bxs) {
          // jge _@seek2a: sub bp,160 ; add ecx,flip(2560) ; adc ecx ; adc cx
          bp = (bp - 160) & 0xffff;
          sum = ecx + STEP1;
          cf = sum > 0xffffffff ? 1 : 0;
          ecx = sum >>> 0;
          sum = ecx + STEP1 + cf;
          cf = sum > 0xffffffff ? 1 : 0;
          ecx = sum >>> 0;
          if (cf) ecx = ((ecx & 0xffff0000) | (((ecx & 0xffff) + 1) & 0xffff)) >>> 0;
          bp = (bp - 160) & 0xffff;
          break hit;
        }
        sum = eax + step;
        cf = sum > 0xffffffff ? 1 : 0;
        eax = sum >>> 0;
        if (cf) eax = ((eax & 0xffff0000) | (((eax & 0xffff) + 1) & 0xffff)) >>> 0;
        vbuf[(bp - 320) & 0xffff] = colour;
        // add ecx,flip(3*2560) ; adc cx,0 ; sub bp,160*3
        sum = ecx + STEP3;
        cf = sum > 0xffffffff ? 1 : 0;
        ecx = sum >>> 0;
        if (cf) ecx = ((ecx & 0xffff0000) | (((ecx & 0xffff) + 1) & 0xffff)) >>> 0;
        bp = (bp - 480) & 0xffff;
        if ((eax << 16 >> 16) >= bxs) break hit;
      }
    }
    // _@seeko: add eax,ecx (; adc eax,ecx in far blocks) ; adc ax,-1
    let sum = eax + ecx;
    cf = sum > 0xffffffff ? 1 : 0;
    eax = sum >>> 0;
    if (far) {
      sum = eax + ecx + cf;
      cf = sum > 0xffffffff ? 1 : 0;
      eax = sum >>> 0;
    }
    const lo = ((eax & 0xffff) + 0xffff + cf) & 0xffff;
    eax = ((eax & 0xffff0000) | lo) >>> 0;
  }
}

// ASM.ASM docopy with PXLSUX disabled: clear the 18 page rows above the
// landscape, copy vbuf rows 60..199 to page rows 70..209 (planes 0,1 take
// the even-column half, planes 2,3 the odd half — 2x pixel doubling), then
// clear vbuf rows 68..97 for the next frame.
function docopy(pageBase) {
  const clearFrom = pageBase + 52 * 80;
  for (let plane = 0; plane < 4; plane++)
    planes.fill(0, plane * 65536 + clearFrom, plane * 65536 + clearFrom + 18 * 80);
  let src = 60 * 160;
  let dst = pageBase + 70 * 80;
  for (let row = 0; row < 140; row++) {
    for (let k = 0; k < 80; k++) {
      const even = vbuf[src + k];
      const odd = vbuf[src + 80 + k];
      planes[dst + k] = even;
      planes[65536 + dst + k] = even;
      planes[2 * 65536 + dst + k] = odd;
      planes[3 * 65536 + dst + k] = odd;
    }
    src += 160;
    dst += 80;
  }
  vbuf.fill(0, 68 * 160, 98 * 160);
}

function drawFrame() {
  rot2 = (rot2 + 4) << 16 >> 16;
  rot = (rot + trunc(sin1024[rot2 & 1023] / 15)) << 16 >> 16;
  const r = rot >> 3;
  const rsin = sin1024[r & 1023];
  const rcos = sin1024[(r + 256) & 1023];
  const rsin2 = sin1024[(r + 177) & 1023];
  const rcos2 = sin1024[(r + 177 + 256) & 1023];
  const xw = xwav;
  const yw = ywav;
  for (let a = 0; a < 160; a++) {
    const x = a - 80;
    const xa = trunc((x * rcos + 160 * rsin) / 256);
    const ya = trunc((160 * rcos2 - x * rsin2) / 256);
    const b = (a & 1) * 80 + (a >> 1) + 199 * 160;
    theloop(xw, yw, xa, ya, b);
    if (a === 80) {
      xwav = (xwav + xa * 4) << 16 >> 16;
      ywav = (ywav + ya * 4) << 16 >> 16;
    }
  }
  flip++;
  if (flip > 1) flip = 0;
  if (flip === 0) {
    displayStart = 0x8000;              // outp(0x3d5,0x80): show page B
    docopy(80 * startrise);             // draw page A (0xa000+5*startrise)
  } else {
    displayStart = 0x0000;              // outp(0x3d5,0x00): show page A
    docopy(0x8000 + 80 * startrise);    // draw page B (0xa800+5*startrise)
  }
}

function stepOne(sampleAt) {
  const now = localFrame / VBLANK_HZ;
  const position = musicPosition(sampleAt ? sampleAt(now) : -32);

  // `while(!dis_exit() && dis_musplus()<0);` — nothing draws before the
  // music position crosses zero.
  if (!musicGateOpen) {
    if (position.musplus < 0) return;
    musicGateOpen = true;
  }
  const a = position.musplus;
  // `while(!dis_exit() && frame<4444)` with `if(a>-8 && a<0) break;`
  if (position.exit || (a > -8 && a < 0) || drawnFrames >= 4444) {
    done = true;
    doneAtLocal = now;
    return;
  }
  // The frepeat block runs once per vblank in this per-step model.
  if (a > -30 && a < 0 && startrise < 160) startrise += 1;
  if (drawnFrames < 400 && startrise > 0) {
    // frame==4 re-sends the palette that is already loaded — no-op here.
    startrise -= 1;
  }
  drawFrame();
  drawnFrames++;
}

function composeDisplay() {
  const start = displayStart;
  let out = 0;
  for (let y = 0; y < HEIGHT; y++) {
    let addr = start + y * 80;
    for (let col = 0; col < 80; col++, addr++) {
      sinfieldVram[out++] = planes[addr];
      sinfieldVram[out++] = planes[65536 + addr];
      sinfieldVram[out++] = planes[2 * 65536 + addr];
      sinfieldVram[out++] = planes[3 * 65536 + addr];
    }
  }
}

export function sinfieldEnded() { return done; }
export function sinfieldLocalFrames() { return localFrame; }
export function sinfieldDurationS() {
  return doneAtLocal ?? Math.max(0, localFrame) / VBLANK_HZ;
}

export function sinfieldStepTo(tt, replay, musplusAtLocal) {
  if (done) return false;
  const target = Math.floor(tt * VBLANK_HZ);
  let steps = target - localFrame;
  if (steps <= 0) return true;
  if (steps > 35 && !replay) steps = 35;
  for (let i = 0; i < steps && !done; i++) {
    localFrame++;
    stepOne(musplusAtLocal);
  }
  composeDisplay();
  return !done;
}
